Neos:
  Neos:
    modules:
      'management':
        submodules:
          'documentationModule':
            label: 'UpAssist.DocumentationReader:Main:module.label'
            controller: 'UpAssist\DocumentationReader\Controller\Backend\Module\DocumentationReaderController'
            description: 'UpAssist.DocumentationReader:Main:module.description'
            icon: 'fas fa-book'
            additionalResources:
              styleSheets:
                - 'resource://UpAssist.DocumentationReader/Public/css/module.css'
    userInterface:
      translation:
        autoInclude:
          UpAssist.DocumentationReader:
            - 'Main'
  Fusion:
    defaultContext:
      Markdown: UpAssist\DocumentationReader\Eel\MarkdownHelper
UpAssist:
  DocumentationReader:
    # The url to your documentation (deprecated)
    # documentationUrl: ''
    # The endpoints for your documentation
    documentationEndpoints:
      - label: 'Neos Documentation'
        url: 'https://www.neos.io/docs-and-support/editor-documentation/administration-interface.html'
